### PR TITLE
A safer CSV example

### PR DESCRIPTION
**Pull request by Tux**
This is docs-only. The change to the tests is just as simple, but requires adding test-time dependencies

### CODE REVIEW

**Review by balajirama — APPROVED** [review]

**Review by balajirama — APPROVED** [review]

**Comment by balajirama** [comment]
I use Dist::Zilla and it will detect all test time dependencies. So feel free to add the tests. My suggestions is to create a new test script and not to edit the one already present. You can give it a name like "Better-CSV-Parser.t" or something.

**Comment by balajirama** [comment]
Also, I see that you modified only one example. Example 2 is just an extension of that one. Can you fix that also? And I would really appreciate the test file too.

**Comment by Tux** [comment]
I have no idea what exactly you now expect from me. Sorry. You already merged my changes on 04-01-2019, which included two new test files.

**Comment by balajirama** [comment]
I don’t expect anything. Just added a tag to my issues so I can manage my own repo better.

**Pull request merged**
